spring:
  datasource:
    driverClassName: com.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_LOCAL_PORT:5433}/${POSTGRESQL_DATABASE:tenant1}?useSSL=false
    username: postgres
    password: 123456

  liquibase:
    enabled: true
    change-log: classpath:/db/db-changelog-master.xml
    drop-first: false

  jpa:
    properties:
      hibernate:
        default_schema: public

default-tenant: tenant1
datasource:
  base-url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/}
  main:
    name: ${MAIN_DB_NAME:tenant1}
    driver: ${MAIN_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${MAIN_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tenant1}
    username: ${MAIN_DATASOURCE_USERNAME:postgres}
    password: ${MAIN_DATASOURCE_PASSWORD:123456}

driver: org.postgresql.Driver
url: ${spring.datasource.url}
username: ${spring.datasource.username}
password: ${spring.datasource.password}
